gripperone:
  moveit_sim_hw_interface:
    joint_model_group: arm
    joint_model_group_pose: straight
# Settings for ros_control_boilerplate control loop
  generic_hw_control_loop:
    loop_hz: 300
    cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
  hardware_interface:
    joints:
      - Rev1
      - Rev2
      - Rev3
      - Rev4
      - Rev5
      - Rev6
      - Rev7
    sim_control_mode: 1 
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev1
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev2
    pid: {p: 2000.0, i: 0.01, d: 50.0}
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev3
    pid: {p: 2000.0, i: 0.01, d: 10.0}
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev4
    pid: {p: 2000.0, i: 0.01, d: 10.0}
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev5
    pid: {p: 2000.0, i: 0.01, d: 10.0}
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev6
    pid: {p: 10.0, i: 0.01, d: 10.0}
  joint7_position_controller:
    type: effort_controllers/JointPositionController
    joint: Rev7
    pid: {p: 10.0, i: 0.01, d: 10.0}
  

