controller_list:
  - name: fake_arm_controller
    type: $(arg execution_type)
    joints:
      - Rev1
      - Rev2
      - Rev3
      - Rev4
  - name: fake_hand_controller
    type: $(arg execution_type)
    joints:
      - Rev5
      - Rev6
      - Rev7
initial:  # Define initial robot poses.
  - group: arm
    pose: straight